apiVersion: v1 # k8s master apiversion
kind: Pod # we are requisting for POD 
metadata: # info about POD 
 namespace: ashu-project
 name: ashupod123 # name of the poD 
 labels: # to define label of pod
  x: helloashu # here x is a key and helloashu is value 
spec: # info About your container
 containers:
 - name: ashuc1 
   image: dockerashu/httpd:ashuciscov111
   ports:
   - containerPort: 80

# adding service yaml here only 

---

apiVersion: v1
kind: Service 
metadata:
  namespace: ashu-project
  creationTimestamp: null
  labels: # label of service 
    app: ashusvc1
  name: ashusvc1 # name of service 
spec:
  ports:
  - name: 1234-80
    port: 1234 # service port that will be bounded with service IP 
    protocol: TCP
    targetPort: 80 # pod application port 
  selector: # POD finder 
    x: helloashu # exactly same label as pod have  type: NodePort # type of service 
status:
  loadBalancer: {}

 